[package]
name = "regel-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
regel-audio = { path = "../regel-audio" }
regel-engine = { path = "../regel-engine" }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
