#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    ldconfig || true
    if command -v update-icon-caches >/dev/null 2>&1; then
        update-icon-caches /usr/share/icons/hicolor || true
    fi
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications || true
    fi
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --global daemon-reload 2>/dev/null || true
    fi
fi

#DEBHELPER#

exit 0
