#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    vec2 u_resolution;
    vec2 u_pointer;
    vec2 u_pointer_vel;
    vec2 u_keystroke_pos;
    vec2 u_keystroke_dir;
    vec2 u_beat_center;
    vec2 u_ambient_drift;
    vec4 u_color_water;
    vec4 u_color_pebbles;
    vec4 u_color_caustics;
    vec4 u_color_accent;
    float u_time;
    float u_keystroke_energy;
    float u_shockwave_intensity;
    float u_vortex_speed;
    float u_bass;
    float u_mids;
    float u_treble;
    float u_water_clarity;
};

// --- Fast GPU Simplex Noise & Hash ---
vec2 hash22(vec2 p) {
    p = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
    return -1.0 + 2.0 * fract(sin(p) * 43758.5453123);
}

float noise2D(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * (3.0 - 2.0 * f);

    return mix(mix(dot(hash22(i + vec2(0.0, 0.0)), f - vec2(0.0, 0.0)),
                   dot(hash22(i + vec2(1.0, 0.0)), f - vec2(1.0, 0.0)), u.x),
               mix(dot(hash22(i + vec2(0.0, 1.0)), f - vec2(0.0, 1.0)),
                   dot(hash22(i + vec2(1.0, 1.0)), f - vec2(1.0, 1.0)), u.x), u.y);
}

float fbm(vec2 p) {
    float v = 0.0;
    float a = 0.5;
    mat2 rot = mat2(cos(0.5), sin(0.5), -sin(0.5), cos(0.5));
    for (int i = 0; i < 4; ++i) {
        v += a * noise2D(p);
        p = rot * p * 2.05 + vec2(1.3, 0.7);
        a *= 0.5;
    }
    return v;
}

// Voronoi cellular distance field for smooth riverbed pebbles
vec3 voronoiPebbles(vec2 p) {
    vec2 n = floor(p);
    vec2 f = fract(p);
    vec2 mg, mr;
    float md = 8.0;
    for (int j = -1; j <= 1; ++j) {
        for (int i = -1; i <= 1; ++i) {
            vec2 g = vec2(float(i), float(j));
            vec2 o = hash22(n + g) * 0.35 + 0.5;
            vec2 r = g + o - f;
            float d = dot(r, r);
            if (d < md) {
                md = d;
                mr = r;
                mg = g;
            }
        }
    }
    return vec3(sqrt(md), hash22(n + mg));
}

// Light caustics generated by refracted water surface waves
float evaluateCaustics(vec2 p, float t) {
    vec2 p1 = p * 12.0 + vec2(t * 0.20, -t * 0.15);
    vec2 p2 = p * 15.0 - vec2(-t * 0.15, t * 0.22);
    float c1 = pow(clamp(1.0 - abs(sin(p1.x + sin(p1.y * 1.4) + cos(p2.x * 0.9))), 0.0, 1.0), 2.5);
    float c2 = pow(clamp(1.0 - abs(cos(p2.y + cos(p2.x * 1.3) + sin(p1.y * 0.8))), 0.0, 1.0), 2.5);
    return (c1 + c2) * 0.5;
}

// Evaluates a single procedurally animated Nishikigoi (Koi) with undulating spine
float evaluateKoi(
    vec2 p,
    vec2 headPos,
    vec2 swimHeading,
    float fishLength,
    float t,
    int morph,
    float audioFlick,
    out float shadowMask,
    out vec3 bodyColor
) {
    vec2 heading = normalize(swimHeading + vec2(0.0001));
    vec2 sideNorm = vec2(-heading.y, heading.x);
    vec2 rel = p - headPos;

    // Project coordinate onto longitudinal and lateral spine axes
    float s = dot(rel, -heading);
    float v = dot(rel, sideNorm);

    // Fast bounding box rejection
    if (s < -0.04 || s > fishLength * 1.35 || abs(v) > fishLength * 0.45) {
        shadowMask = 0.0;
        bodyColor = vec3(0.0);
        return 0.0;
    }

    float u = s / fishLength; // Normalized spine progression [0.0 = snout, 1.0 = caudal peduncle]

    // Procedural multi-segment spine undulation wave (serene, natural tail stroke)
    float swimCadence = t * 5.0 + audioFlick * 0.4;
    float spineWave = sin(u * 6.5 - swimCadence);
    float lateralSway = 0.022 * u * u * spineWave;
    float localV = v - lateralSway;

    // Body half-width profile along spine
    float wSnout = sqrt(clamp(u / 0.25, 0.0, 1.0));
    float wBody = 1.0 - 0.72 * smoothstep(0.25, 0.85, u);
    float finFan = smoothstep(0.85, 1.05, u) * (1.0 - smoothstep(1.05, 1.25, u)) * 0.85;
    float maxHalfWidth = fishLength * 0.21;
    float halfWidth = maxHalfWidth * (wSnout * wBody + finFan);

    // Lateral profile distance
    float bodyNormDist = abs(localV) / max(0.0001, halfWidth);
    float inBody = 1.0 - smoothstep(0.85, 1.0, bodyNormDist);

    // Pectoral Fins (flare on sides)
    float pectDist = length(vec2((u - 0.32) * 1.5, abs(v) - halfWidth * 1.35));
    float pectFin = (1.0 - smoothstep(0.015, 0.045, pectDist)) * smoothstep(0.18, 0.35, u) * 0.8;

    // Caudal Tail Fin (translucent veil tail with rayed striations)
    float tailDist = length(vec2((u - 1.05) * 1.2, abs(localV) * 0.9));
    float tailRays = sin(localV * 140.0) * 0.15;
    float tailFin = (1.0 - smoothstep(0.02, 0.07, tailDist)) * smoothstep(0.85, 1.0, u) * (0.85 + tailRays);

    float totalFishCoverage = clamp(inBody + pectFin + tailFin, 0.0, 1.0);

    // Fish drop shadow onto riverbed with sun angle offset
    vec2 sunOffset = vec2(0.022, -0.032);
    vec2 relShadow = (p - sunOffset) - headPos;
    float sShad = dot(relShadow, -heading);
    float vShad = dot(relShadow, sideNorm) - lateralSway;
    float uShad = sShad / fishLength;
    float wShad = maxHalfWidth * (sqrt(clamp(uShad / 0.25, 0.0, 1.0)) * (1.0 - 0.72 * smoothstep(0.25, 0.85, uShad)));
    shadowMask = (1.0 - smoothstep(0.8, 1.3, abs(vShad) / max(0.0001, wShad))) * smoothstep(-0.02, 0.05, uShad) * (1.0 - smoothstep(0.85, 1.1, uShad)) * 0.65;

    // --- Nishikigoi Traditional Pigment Morphs ---
    vec3 baseWhite = vec3(0.96, 0.95, 0.93);
    vec3 scarletHi = vec3(0.92, 0.12, 0.05); // Rich Japanese cinnabar red
    vec3 sumiBlack = vec3(0.04, 0.05, 0.07); // Ink black
    vec3 goldOgon = vec3(1.0, 0.65, 0.08);   // Metallic gold
    vec3 platinum = vec3(0.92, 0.94, 0.98);

    // Procedural organic pigment pattern mapped to spine coordinates
    vec2 patUV = vec2(u * 4.5, localV * 25.0);
    float hiPattern = smoothstep(0.46, 0.52, fbm(patUV));
    float sumiPattern = smoothstep(0.62, 0.68, fbm(patUV + vec2(2.5, 4.0)));

    vec3 col = baseWhite;

    if (morph == 0) {
        // Kohaku (White body with scarlet Hi islands)
        col = mix(baseWhite, scarletHi, hiPattern);
    } else if (morph == 1) {
        // Taisho Sanke (White + scarlet Hi + sumi black spots)
        col = mix(baseWhite, scarletHi, hiPattern);
        col = mix(col, sumiBlack, sumiPattern);
    } else if (morph == 2) {
        // Yamabuki Ogon (Radiant metallic gold/amber with scale shimmer)
        float scales = sin(u * 65.0) * cos(localV * 85.0) * 0.15;
        col = goldOgon + vec3(scales);
    } else if (morph == 3) {
        // Tancho Ghost Koi (Silvery platinum body + scarlet sun spot on head)
        float sunSpot = 1.0 - smoothstep(0.028, 0.038, length(vec2(u - 0.16, localV * 1.5)));
        col = mix(platinum, scarletHi, sunSpot);
    } else {
        // Showa Sanshoku (Black base with bold scarlet and white marks)
        col = sumiBlack;
        col = mix(col, scarletHi, hiPattern);
        col = mix(col, baseWhite, sumiPattern * (1.0 - hiPattern));
    }

    // 3D Dorsal Curvature & Specular Highlight
    float spineDepth = sqrt(max(0.0, 1.0 - bodyNormDist * bodyNormDist));
    vec3 lightDir = normalize(vec3(0.5, 0.6, 0.8));
    vec3 normal = normalize(vec3(-localV / max(0.001, halfWidth), -0.2, spineDepth));
    float spec = pow(clamp(dot(normal, lightDir), 0.0, 1.0), 12.0) * 0.6;
    col += vec3(spec);

    // Translucency for fins
    if (inBody < 0.2) {
        col = mix(col, vec3(0.9, 0.95, 1.0), 0.4);
    }

    bodyColor = col;
    return totalFishCoverage;
}

// Evaluates floating circular lily pads
float evaluateLilyPad(
    vec2 p,
    vec2 center,
    float radius,
    float angleNotch,
    float t,
    out float padShadow,
    out vec3 padColor
) {
    vec2 toPad = p - center;
    float dist = length(toPad);
    float padAngle = atan(toPad.y, toPad.x);

    // Radial pie notch (characteristic water lily slit)
    float dAngle = mod(padAngle - angleNotch + 3.14159, 6.28318) - 3.14159;
    float inNotch = smoothstep(0.01, 0.14, abs(dAngle) - 0.16);

    float inPad = (1.0 - smoothstep(radius - 0.006, radius, dist)) * inNotch;

    // Drop shadow on pond floor
    vec2 sOffset = vec2(0.032, -0.042);
    float sDist = length(p - (center + sOffset));
    padShadow = (1.0 - smoothstep(radius - 0.015, radius + 0.025, sDist)) * inNotch * 0.70;

    // Chlorophyll vein structure & edge rim
    float veins = smoothstep(0.94, 1.0, cos(padAngle * 14.0)) * (1.0 - dist / radius);
    float rim = smoothstep(radius - 0.018, radius, dist);
    vec3 deepGreen = vec3(0.06, 0.32, 0.12);
    vec3 brightGreen = vec3(0.18, 0.58, 0.22);
    vec3 yellowRim = vec3(0.48, 0.62, 0.16);
    vec3 col = mix(deepGreen, brightGreen, veins * 0.45);
    col = mix(col, yellowRim, rim * 0.75);

    padColor = col;
    return inPad;
}

void main() {
    vec2 uv = qt_TexCoord0;
    float aspect = u_resolution.x / max(u_resolution.y, 1.0);
    vec2 p = uv;
    p.x *= aspect;

    vec2 centerP = vec2(0.5 * aspect, 0.5);

    // --- Interactive Coordinates ---
    vec2 pointerP = u_pointer;
    pointerP.x *= aspect;

    vec2 keystrokeP = u_keystroke_pos;
    keystrokeP.x *= aspect;

    vec2 beatCenterP = u_beat_center;
    beatCenterP.x *= aspect;

    float t = u_time * u_vortex_speed;
    float mouseSpeed = length(u_pointer_vel);
    float predatorPanic = smoothstep(0.06, 0.35, mouseSpeed);
    float feedAttract = smoothstep(0.04, 0.70, u_keystroke_energy);

    // ------------------------------------------------------------------------
    // 1. Water Surface Wave Dynamics (Tranquil & Glassy)
    // ------------------------------------------------------------------------
    // Ambient gentle surface ripples
    vec2 rippleUV = p * 16.0 + u_ambient_drift * 2.0;
    float wave1 = sin(rippleUV.x * 1.8 + t * 1.5) * cos(rippleUV.y * 1.5 - t * 1.2);
    float wave2 = cos(rippleUV.x * 2.5 - t * 1.8) * sin(rippleUV.y * 2.0 + t * 1.5);
    float waveHeight = (wave1 + wave2 * 0.6) * 0.0035;

    // Keystroke concentric raindrop ripples (gentle droplets)
    if (u_keystroke_energy > 0.01) {
        float rDist = length(p - keystrokeP);
        float rainWave = sin(rDist * 36.0 - t * 10.0) * exp(-rDist * 7.0) * u_keystroke_energy * 0.008;
        waveHeight += rainWave;
    }

    // Pointer movement water wake (smooth, natural displacement)
    float mouseDist = length(p - pointerP);
    float mouseWake = sin(mouseDist * 22.0 - t * 3.0) * exp(-mouseDist * 9.0) * mouseSpeed * 0.004;
    waveHeight += mouseWake;

    // Audio Sub-bass cymatic surface waves (subtle and soft)
    float beatDist = length(p - beatCenterP);
    float bassWave = sin(beatDist * 22.0 - t * 6.0) * exp(-beatDist * 5.0) * u_bass * 0.005;
    waveHeight += bassWave;

    // Auth Failed squall (muted)
    if (u_shockwave_intensity > 0.01) {
        float squall = sin(p.x * 40.0 + t * 12.0) * cos(p.y * 36.0 - t * 10.0) * u_shockwave_intensity * 0.012;
        waveHeight += squall;
    }

    // Water surface normal for light refraction (proper central finite difference)
    const float eps = 0.008;
    vec2 pDx = p + vec2(eps, 0.0);
    vec2 pDy = p + vec2(0.0, eps);
    vec2 ripDx = pDx * 16.0 + u_ambient_drift * 2.0;
    vec2 ripDy = pDy * 16.0 + u_ambient_drift * 2.0;
    float hDx = (sin(ripDx.x * 1.8 + t * 1.5) * cos(ripDx.y * 1.5 - t * 1.2) + cos(ripDx.x * 2.5 - t * 1.8) * sin(ripDx.y * 2.0 + t * 1.5) * 0.6) * 0.0035;
    float hDy = (sin(ripDy.x * 1.8 + t * 1.5) * cos(ripDy.y * 1.5 - t * 1.2) + cos(ripDy.x * 2.5 - t * 1.8) * sin(ripDy.y * 2.0 + t * 1.5) * 0.6) * 0.0035;
    vec2 waterGradient = vec2(hDx - (wave1 + wave2 * 0.6) * 0.0035, hDy - (wave1 + wave2 * 0.6) * 0.0035) / eps;
    vec3 waterNormal = normalize(vec3(-waterGradient.x * 0.8, -waterGradient.y * 0.8, 0.65));

    // Refracted UV for looking through the water volume onto the pond bed
    vec2 refrUV = p + waterNormal.xy * 0.020;

    // ------------------------------------------------------------------------
    // 2. Riverbed Pebbles, Granite & Mossy Substrate
    // ------------------------------------------------------------------------
    vec3 pebbleVor = voronoiPebbles(refrUV * 12.0);
    float pebbleDist = pebbleVor.x;
    vec2 pebbleRand = pebbleVor.yz;

    // Palette blending for pebbles
    vec3 pebbleCol1 = u_color_pebbles.rgb;
    vec3 pebbleCol2 = u_color_pebbles.rgb * vec3(0.7, 0.8, 0.75); // Slate riverbed
    vec3 pebbleCol3 = vec3(0.12, 0.22, 0.15);                     // Submerged moss green

    vec3 bedColor = mix(pebbleCol1, pebbleCol2, pebbleRand.x);
    // Moss patches nestled in rock crevices
    float moss = smoothstep(0.45, 0.70, fbm(refrUV * 18.0));
    bedColor = mix(bedColor, pebbleCol3, moss * 0.7);

    // Pebble 3D bevel shading
    float pebbleBevel = smoothstep(0.04, 0.15, pebbleDist);
    bedColor *= (0.65 + 0.35 * pebbleBevel);

    // Sunlight Caustics Network dancing across riverbed (calm, gentle refraction)
    float caustics = evaluateCaustics(refrUV, t) * (0.85 + u_treble * 0.35);
    bedColor += u_color_caustics.rgb * caustics * 0.75;

    // ------------------------------------------------------------------------
    // 3. Multi-Agent Nishikigoi School (5 Autonomous Koi Boids)
    // ------------------------------------------------------------------------
    float totalShadow = 0.0;
    float totalFishMask = 0.0;
    vec3 totalFishColor = vec3(0.0);

    // Autonomous trajectories with flocking, predator avoidance & food seeking
    float audioFlick = u_bass * 0.20;

    for (int i = 0; i < 5; ++i) {
        float fi = float(i);
        float orbitAngle = t * (0.18 + fi * 0.02) + fi * 1.25;
        float orbitRadiusX = (0.24 + fi * 0.05) * aspect;
        float orbitRadiusY = 0.16 + fi * 0.03;

        vec2 basePos = centerP + vec2(cos(orbitAngle) * orbitRadiusX, sin(orbitAngle * 1.2) * orbitRadiusY);
        vec2 heading = vec2(-sin(orbitAngle) * orbitRadiusX, cos(orbitAngle * 1.2) * orbitRadiusY * 1.2);

        // Predator Avoidance (gentle avoidance, glide away without frantic panic)
        vec2 toPointer = basePos - pointerP;
        vec2 panicDir = normalize(toPointer + vec2(0.001));
        basePos += panicDir * predatorPanic * (0.05 + fi * 0.015);

        // Chemotaxis Food Seeking (swim toward keystroke nutrient pellets)
        vec2 feedDir = normalize(keystrokeP - basePos + vec2(0.001));
        basePos = mix(basePos, keystrokeP, feedAttract * (0.35 + fi * 0.08));

        // Dynamically steer fish heading along real locomotion trajectory
        vec2 dynamicHeading = heading;
        dynamicHeading += panicDir * predatorPanic * 0.45;
        dynamicHeading = mix(dynamicHeading, feedDir, feedAttract * 0.75);
        heading = normalize(dynamicHeading + vec2(0.0001));

        float fishLen = 0.14 + fi * 0.015;
        float shad = 0.0;
        vec3 fCol = vec3(0.0);
        float mask = evaluateKoi(p, basePos, heading, fishLen, t + fi * 3.0, i, audioFlick, shad, fCol);

        totalShadow = max(totalShadow, shad);
        if (mask > 0.01) {
            totalFishColor = mix(totalFishColor, fCol, mask);
            totalFishMask = max(totalFishMask, mask);
        }
    }

    // Apply fish drop shadow to riverbed
    bedColor *= (1.0 - totalShadow * 0.65);

    // Composite fish over riverbed
    vec3 pondContent = mix(bedColor, totalFishColor, totalFishMask);

    // ------------------------------------------------------------------------
    // 4. Floating Lily Pads (Nymphaeaceae)
    // ------------------------------------------------------------------------
    float totalPadShadow = 0.0;
    float totalPadMask = 0.0;
    vec3 totalPadColor = vec3(0.0);

    // 3 Floating Lily Pads anchored around pond edges
    vec2 padPos[3];
    padPos[0] = centerP + vec2(-0.28 * aspect, 0.22);
    padPos[1] = centerP + vec2(0.32 * aspect, -0.18);
    padPos[2] = centerP + vec2(-0.15 * aspect, -0.26);

    float padRadius[3] = float[3](0.11, 0.13, 0.095);
    float padNotch[3] = float[3](0.8, -1.2, 2.4);

    for (int k = 0; k < 3; ++k) {
        float pShad = 0.0;
        vec3 pCol = vec3(0.0);
        float pMask = evaluateLilyPad(p, padPos[k], padRadius[k], padNotch[k], t, pShad, pCol);
        totalPadShadow = max(totalPadShadow, pShad);
        if (pMask > 0.01) {
            totalPadColor = mix(totalPadColor, pCol, pMask);
            totalPadMask = max(totalPadMask, pMask);
        }
    }

    // Apply lily pad shadows
    pondContent *= (1.0 - totalPadShadow * 0.70);
    pondContent = mix(pondContent, totalPadColor, totalPadMask);

    // ------------------------------------------------------------------------
    // 5. Crystal Clear Water Volume, Depth Absorption & Sky Fresnel
    // ------------------------------------------------------------------------
    vec3 waterTint = u_color_water.rgb;
    // Water depth absorption (Beer-Lambert attenuation)
    vec3 finalColor = mix(pondContent, waterTint, 0.22);

    // Surface specular sunlight glint from sky reflection
    vec3 sunLight = normalize(vec3(0.45, 0.55, 0.75));
    vec3 eyeDir = vec3(0.0, 0.0, 1.0);
    vec3 halfVec = normalize(sunLight + eyeDir);
    float waterSpec = pow(clamp(dot(waterNormal, halfVec), 0.0, 1.0), 32.0);
    finalColor += vec3(waterSpec * 0.85);

    // Keystroke glowing food pellets sinking in water
    if (u_keystroke_energy > 0.01) {
        float pelletDist = length(p - keystrokeP);
        float pelletGlow = exp(-pelletDist * 32.0) * (0.8 + 0.5 * sin(t * 8.0)) * u_keystroke_energy;
        finalColor += u_color_accent.rgb * pelletGlow * 2.0;
    }

    // Auth Failed Lightning Flash
    if (u_shockwave_intensity > 0.01) {
        float lightningFlash = u_shockwave_intensity * (0.7 + 0.3 * sin(t * 40.0));
        finalColor += vec3(0.85, 0.90, 1.0) * lightningFlash * 0.75;
    }

    fragColor = vec4(finalColor, 1.0) * qt_Opacity;
}
