#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    vec2 u_resolution;
    vec2 u_pointer;
    vec2 u_pointer_vel;
    vec2 u_keystroke_pos;
    vec2 u_keystroke_dir;
    vec2 u_beat_center;
    vec2 u_ambient_drift;
    vec4 u_color_water;
    vec4 u_color_pebbles;
    vec4 u_color_caustics;
    vec4 u_color_accent;
    float u_time;
    float u_keystroke_energy;
    float u_shockwave_intensity;
    float u_vortex_speed;
    float u_bass;
    float u_mids;
    float u_treble;
    float u_water_clarity;

    // 5 Animated Lily Pads (2 x vec4 per pad = 160B)
    vec4 u_pad0_geo;
    vec4 u_pad1_geo;
    vec4 u_pad2_geo;
    vec4 u_pad3_geo;
    vec4 u_pad4_geo;

    vec4 u_pad0_dyn;
    vec4 u_pad1_dyn;
    vec4 u_pad2_dyn;
    vec4 u_pad3_dyn;
    vec4 u_pad4_dyn;

    // 5 Active Fish Agents (2 x vec4 per fish = 160B)
    vec4 u_fish0_pos;
    vec4 u_fish1_pos;
    vec4 u_fish2_pos;
    vec4 u_fish3_pos;
    vec4 u_fish4_pos;

    vec4 u_fish0_attr;
    vec4 u_fish1_attr;
    vec4 u_fish2_attr;
    vec4 u_fish3_attr;
    vec4 u_fish4_attr;
};

// --- Fast GPU Simplex Noise & Hash ---
vec2 hash22(vec2 p) {
    p = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
    return -1.0 + 2.0 * fract(sin(p) * 43758.5453123);
}

float noise2D(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * (3.0 - 2.0 * f);

    return mix(mix(dot(hash22(i + vec2(0.0, 0.0)), f - vec2(0.0, 0.0)),
                   dot(hash22(i + vec2(1.0, 0.0)), f - vec2(1.0, 0.0)), u.x),
               mix(dot(hash22(i + vec2(0.0, 1.0)), f - vec2(0.0, 1.0)),
                   dot(hash22(i + vec2(1.0, 1.0)), f - vec2(1.0, 1.0)), u.x), u.y);
}

float fbm(vec2 p) {
    float v = 0.0;
    float a = 0.5;
    mat2 rot = mat2(cos(0.5), sin(0.5), -sin(0.5), cos(0.5));
    for (int i = 0; i < 4; ++i) {
        v += a * noise2D(p);
        p = rot * p * 2.05 + vec2(1.3, 0.7);
        a *= 0.5;
    }
    return v;
}

// Voronoi cellular distance field for smooth riverbed pebbles
vec3 voronoiPebbles(vec2 p) {
    vec2 n = floor(p);
    vec2 f = fract(p);
    vec2 mg, mr;
    float md = 8.0;
    for (int j = -1; j <= 1; ++j) {
        for (int i = -1; i <= 1; ++i) {
            vec2 g = vec2(float(i), float(j));
            vec2 o = hash22(n + g) * 0.35 + 0.5;
            vec2 r = g + o - f;
            float d = dot(r, r);
            if (d < md) {
                md = d;
                mr = r;
                mg = g;
            }
        }
    }
    return vec3(sqrt(md), hash22(n + mg));
}

// Light caustics generated by refracted water surface waves
float evaluateCaustics(vec2 p, float t) {
    vec2 p1 = p * 12.0 + vec2(t * 0.20, -t * 0.15);
    vec2 p2 = p * 15.0 - vec2(-t * 0.15, t * 0.22);
    float c1 = pow(clamp(1.0 - abs(sin(p1.x + sin(p1.y * 1.4) + cos(p2.x * 0.9))), 0.0, 1.0), 2.5);
    float c2 = pow(clamp(1.0 - abs(cos(p2.y + cos(p2.x * 1.3) + sin(p1.y * 0.8))), 0.0, 1.0), 2.5);
    return (c1 + c2) * 0.5;
}

// --- 12-Variety Authentic Nishikigoi Phenotypic Specification ---
struct KoiPhenotype {
    vec3 baseColor;
    vec3 secondaryColor;
    vec3 accentColor;
    int patternMode;    // 0: Metallic, 1: Plates, 2: Tri-color, 3: Crown spot, 4: Reticulated net, 5: Doitsu zipper, 6: Shadow
    float scaleShimmer;
    float finMultiplier;
};

KoiPhenotype getKoiPhenotype(int variety) {
    KoiPhenotype p;
    p.scaleShimmer = 0.0;
    p.finMultiplier = 1.0;

    int v = variety % 12;
    if (v == 0) {
        // 1. Kohaku: Pure white body with bold scarlet Hi plates
        p.baseColor = vec3(0.96, 0.95, 0.93);
        p.secondaryColor = vec3(0.92, 0.12, 0.05);
        p.accentColor = p.baseColor;
        p.patternMode = 1;
    } else if (v == 1) {
        // 2. Taisho Sanke: White base + scarlet plates + sumi ink dots
        p.baseColor = vec3(0.96, 0.95, 0.93);
        p.secondaryColor = vec3(0.92, 0.12, 0.05);
        p.accentColor = vec3(0.04, 0.05, 0.07);
        p.patternMode = 2;
    } else if (v == 2) {
        // 3. Showa Sanshoku: Ink black base with wrapping scarlet and white marks
        p.baseColor = vec3(0.04, 0.05, 0.07);
        p.secondaryColor = vec3(0.92, 0.12, 0.05);
        p.accentColor = vec3(0.96, 0.95, 0.93);
        p.patternMode = 2;
    } else if (v == 3) {
        // 4. Yamabuki Ogon: Brilliant radiant metallic gold with scale shimmer
        p.baseColor = vec3(1.0, 0.68, 0.08);
        p.secondaryColor = vec3(1.0, 0.82, 0.35);
        p.accentColor = vec3(0.85, 0.55, 0.04);
        p.patternMode = 0;
        p.scaleShimmer = 0.85;
    } else if (v == 4) {
        // 5. Tancho: Ethereal silver-white body with solitary crimson crown spot
        p.baseColor = vec3(0.94, 0.96, 0.98);
        p.secondaryColor = vec3(0.94, 0.10, 0.05);
        p.accentColor = p.baseColor;
        p.patternMode = 3;
    } else if (v == 5) {
        // 6. Asagi: Indigo-blue reticulated scale netting + vibrant orange flanks
        p.baseColor = vec3(0.32, 0.42, 0.52);
        p.secondaryColor = vec3(0.92, 0.38, 0.08);
        p.accentColor = vec3(0.12, 0.18, 0.28);
        p.patternMode = 4;
    } else if (v == 6) {
        // 7. Shusui: Doitsu sky-blue mirror skin + dorsal spine zipper scales
        p.baseColor = vec3(0.55, 0.68, 0.78);
        p.secondaryColor = vec3(0.92, 0.35, 0.08);
        p.accentColor = vec3(0.08, 0.12, 0.22);
        p.patternMode = 5;
    } else if (v == 7) {
        // 8. Ki Utsuri: Lacquer black body with bold amber-yellow markings
        p.baseColor = vec3(0.04, 0.05, 0.06);
        p.secondaryColor = vec3(0.98, 0.75, 0.05);
        p.accentColor = p.baseColor;
        p.patternMode = 1;
    } else if (v == 8) {
        // 9. Gin Matsuba: Metallic platinum silver with pinecone scale centers
        p.baseColor = vec3(0.88, 0.90, 0.94);
        p.secondaryColor = vec3(0.20, 0.22, 0.26);
        p.accentColor = vec3(0.10, 0.12, 0.15);
        p.patternMode = 4;
        p.scaleShimmer = 0.75;
    } else if (v == 9) {
        // 10. Chagoi: Warm olive-brown monochrome with peaceful net scaling
        p.baseColor = vec3(0.42, 0.35, 0.22);
        p.secondaryColor = vec3(0.32, 0.26, 0.16);
        p.accentColor = vec3(0.55, 0.46, 0.30);
        p.patternMode = 4;
    } else if (v == 10) {
        // 11. Karasugoi: Crow-black shadow koi with subtle orange belly rim
        p.baseColor = vec3(0.02, 0.02, 0.03);
        p.secondaryColor = vec3(0.85, 0.30, 0.05);
        p.accentColor = vec3(0.06, 0.07, 0.08);
        p.patternMode = 6;
    } else {
        // 12. Butterfly / Hirenaga Koi: Flowing diaphanous fins & pearl luster
        p.baseColor = vec3(0.95, 0.95, 0.98);
        p.secondaryColor = vec3(1.0, 0.78, 0.25);
        p.accentColor = vec3(0.98, 0.98, 1.0);
        p.patternMode = 1;
        p.scaleShimmer = 0.60;
        p.finMultiplier = 2.2;
    }
    return p;
}

// Evaluates a single procedurally animated Nishikigoi (Koi) with undulating spine
float evaluateKoi(
    vec2 p,
    vec2 headPos,
    vec2 swimHeading,
    float fishLength,
    float cadencePhase,
    int variety,
    float depth,
    float audioFlick,
    out float shadowMask,
    out vec3 bodyColor
) {
    vec2 heading = normalize(swimHeading + vec2(0.0001));
    vec2 sideNorm = vec2(-heading.y, heading.x);
    vec2 rel = p - headPos;

    float s = dot(rel, -heading);
    float v = dot(rel, sideNorm);

    KoiPhenotype pheno = getKoiPhenotype(variety);
    float finMult = pheno.finMultiplier;

    // Fast bounding box rejection (including sun shadow margin & butterfly fins)
    vec2 sunOffset = vec2(0.022, -0.032);
    float sShadMargin = length(sunOffset);

    if (s < -0.05 - sShadMargin || s > fishLength * (1.35 + 0.45 * (finMult - 1.0)) || abs(v) > fishLength * (0.45 * finMult)) {
        shadowMask = 0.0;
        bodyColor = vec3(0.0);
        return 0.0;
    }

    float u = s / fishLength; // Normalized spine progression [0.0 = snout, 1.0 = caudal peduncle]

    // Procedural multi-segment spine undulation wave
    float swimCadence = cadencePhase + audioFlick * 0.4;
    float spineWave = sin(u * 6.5 - swimCadence);
    float lateralSway = 0.022 * u * u * spineWave / (1.0 + 0.35 * (finMult - 1.0));
    float localV = v - lateralSway;

    // Body half-width profile along spine
    float wSnout = sqrt(clamp(u / 0.25, 0.0, 1.0));
    float wBody = 1.0 - 0.72 * smoothstep(0.25, 0.85, u);
    float finFan = smoothstep(0.85, 1.05, u) * (1.0 - smoothstep(1.05, 1.25, u)) * 0.85;
    float maxHalfWidth = fishLength * 0.21;
    float halfWidth = maxHalfWidth * (wSnout * wBody + finFan);

    // Lateral profile distance
    float bodyNormDist = abs(localV) / max(0.0001, halfWidth);
    float inBody = 1.0 - smoothstep(0.85, 1.0, bodyNormDist);

    // Pectoral Fins (flare on sides)
    float pectDist = length(vec2((u - 0.32) * 1.5, (abs(v) - halfWidth * 1.35) / max(1.0, finMult * 0.85)));
    float pectFin = (1.0 - smoothstep(0.015 * finMult, 0.045 * finMult, pectDist)) * smoothstep(0.18, 0.35, u) * 0.8;

    // Caudal Tail Fin (translucent veil tail with rayed striations)
    float tailDist = length(vec2((u - (1.05 + 0.12 * (finMult - 1.0))) / max(1.0, finMult * 0.9), abs(localV) * 0.9));
    float tailRays = sin(localV * 140.0) * 0.15;
    float tailFin = (1.0 - smoothstep(0.02 * finMult, 0.07 * finMult, tailDist)) * smoothstep(0.85, 1.0, u) * (0.85 + tailRays);

    float totalFishCoverage = clamp(inBody + pectFin + tailFin, 0.0, 1.0);

    // Fish drop shadow onto riverbed with sun angle offset
    vec2 relShadow = (p - sunOffset) - headPos;
    float sShad = dot(relShadow, -heading);
    float vShad = dot(relShadow, sideNorm) - lateralSway;
    float uShad = sShad / fishLength;
    float wShad = maxHalfWidth * (sqrt(clamp(uShad / 0.25, 0.0, 1.0)) * (1.0 - 0.72 * smoothstep(0.25, 0.85, uShad)));
    shadowMask = (1.0 - smoothstep(0.8, 1.3, abs(vShad) / max(0.0001, wShad))) * smoothstep(-0.02, 0.05, uShad) * (1.0 - smoothstep(0.85, 1.1, uShad)) * 0.65;
    shadowMask *= (1.0 - depth * 0.75);

    // Procedural organic pigment pattern mapped to spine coordinates
    vec2 patUV = vec2(u * 4.5, localV * 25.0);
    float fbmPat1 = fbm(patUV);
    float fbmPat2 = fbm(patUV + vec2(2.5, 4.0));

    vec3 col = pheno.baseColor;

    if (pheno.patternMode == 0) {
        // Metallic monochrome
        float scales = sin(u * 65.0) * cos(localV * 85.0) * 0.15;
        col = pheno.baseColor + vec3(scales * pheno.scaleShimmer);
    } else if (pheno.patternMode == 1) {
        // Plates / stepped marks
        float plates = smoothstep(0.46, 0.52, fbmPat1);
        col = mix(pheno.baseColor, pheno.secondaryColor, plates);
    } else if (pheno.patternMode == 2) {
        // Tri-color speckles
        float hiPattern = smoothstep(0.46, 0.52, fbmPat1);
        float sumiPattern = smoothstep(0.62, 0.68, fbmPat2);
        col = mix(pheno.baseColor, pheno.secondaryColor, hiPattern);
        col = mix(col, pheno.accentColor, sumiPattern * (variety == 2 ? (1.0 - hiPattern * 0.4) : 1.0));
    } else if (pheno.patternMode == 3) {
        // Crown spot
        float sunSpot = 1.0 - smoothstep(0.028, 0.038, length(vec2(u - 0.16, localV * 1.5)));
        col = mix(pheno.baseColor, pheno.secondaryColor, sunSpot);
    } else if (pheno.patternMode == 4) {
        // Reticulated net / pinecone
        float netGrid = smoothstep(0.25, 0.75, sin(u * 60.0) * cos(localV * 80.0));
        vec3 netCol = mix(pheno.baseColor, pheno.accentColor, netGrid * 0.65);
        float flank = smoothstep(0.35, 0.85, bodyNormDist) * smoothstep(0.15, 0.75, u);
        col = mix(netCol, pheno.secondaryColor, flank);
        if (pheno.scaleShimmer > 0.0) {
            col += vec3(netGrid * 0.15 * pheno.scaleShimmer);
        }
    } else if (pheno.patternMode == 5) {
        // Doitsu zipper
        float dorsalZipper = (1.0 - smoothstep(0.0, 0.18, bodyNormDist)) * smoothstep(0.15, 0.90, u);
        float mirrorScale = smoothstep(0.2, 0.8, sin(u * 55.0)) * dorsalZipper;
        float flankOrange = smoothstep(0.45, 0.95, bodyNormDist) * smoothstep(0.20, 0.80, u);
        col = mix(pheno.baseColor, pheno.accentColor, mirrorScale * 0.9);
        col = mix(col, pheno.secondaryColor, flankOrange * 0.85);
    } else if (pheno.patternMode == 6) {
        // Midnight shadow
        float edgeGlow = smoothstep(0.70, 0.98, bodyNormDist) * smoothstep(0.1, 0.9, u);
        col = mix(pheno.baseColor, pheno.secondaryColor, edgeGlow * 0.5);
    }

    // 3D Dorsal Curvature & Specular Highlight
    float spineDepth = sqrt(max(0.0, 1.0 - bodyNormDist * bodyNormDist));
    vec3 lightDir = normalize(vec3(0.5, 0.6, 0.8));
    vec3 normal = normalize(vec3(-localV / max(0.001, halfWidth), -0.2, spineDepth));
    float spec = pow(clamp(dot(normal, lightDir), 0.0, 1.0), 12.0) * (0.6 + 0.3 * pheno.scaleShimmer);
    col += vec3(spec);

    // Translucency for fins
    if (inBody < 0.2) {
        col = mix(col, vec3(0.9, 0.95, 1.0), 0.4);
        if (finMult > 1.5) {
            col += vec3(0.06 * sin(localV * 60.0), 0.05 * cos(u * 40.0), 0.08);
        }
    }

    // Submersion depth blending
    if (depth > 0.01) {
        col = mix(col, u_color_water.rgb, depth * 0.65);
    }

    bodyColor = col;
    return totalFishCoverage;
}

// Evaluates floating circular lily pads
float evaluateLilyPad(
    vec2 p,
    vec2 center,
    float radius,
    float angleNotch,
    float t,
    int padType,
    out float padShadow,
    out vec3 padColor
) {
    vec2 toPad = p - center;
    float distSq = dot(toPad, toPad);
    float rMax = radius * 1.35; // includes shadow margin
    if (distSq > rMax * rMax) {
        padShadow = 0.0;
        padColor = vec3(0.0);
        return 0.0;
    }

    float dist = sqrt(distSq);
    float padAngle = atan(toPad.y, toPad.x);

    // Radial pie notch (characteristic water lily slit)
    float dAngle = mod(padAngle - angleNotch + 3.14159265, 6.2831853) - 3.14159265;
    float inNotch = smoothstep(0.01, 0.14, abs(dAngle) - 0.16);

    float inPad = (1.0 - smoothstep(radius - 0.006, radius, dist)) * inNotch;

    // Drop shadow on pond floor
    vec2 sOffset = vec2(0.032, -0.042);
    vec2 toShadow = p - (center + sOffset);
    float sDist = length(toShadow);
    float sAngle = atan(toShadow.y, toShadow.x);
    float dAngleS = mod(sAngle - angleNotch + 3.14159265, 6.2831853) - 3.14159265;
    float inNotchS = smoothstep(0.01, 0.14, abs(dAngleS) - 0.16);
    padShadow = (1.0 - smoothstep(radius - 0.015, radius + 0.025, sDist)) * inNotchS * 0.70;

    // Chlorophyll vein structure & edge rim
    float veins = smoothstep(0.94, 1.0, cos(padAngle * 14.0)) * (1.0 - dist / radius);
    float rim = smoothstep(radius - 0.018, radius, dist);
    vec3 deepGreen = vec3(0.06, 0.32, 0.12);
    vec3 brightGreen = vec3(0.18, 0.58, 0.22);
    vec3 yellowRim = vec3(0.48, 0.62, 0.16);

    if (padType == 1) {
        deepGreen = vec3(0.04, 0.26, 0.14);
        brightGreen = vec3(0.14, 0.48, 0.20);
        yellowRim = vec3(0.55, 0.35, 0.14);
    } else if (padType == 2) {
        deepGreen = vec3(0.09, 0.38, 0.15);
        brightGreen = vec3(0.24, 0.64, 0.28);
        yellowRim = vec3(0.62, 0.72, 0.18);
    }

    vec3 col = mix(deepGreen, brightGreen, veins * 0.45);
    col = mix(col, yellowRim, rim * 0.75);

    padColor = col;
    return inPad;
}

void main() {
    vec2 uv = qt_TexCoord0;
    float aspect = u_resolution.x / max(u_resolution.y, 1.0);
    vec2 p = uv;
    p.x *= aspect;

    vec2 centerP = vec2(0.5 * aspect, 0.5);

    // --- Unpack Lilypad and Fish Entities ---
    vec4 padGeo[5] = vec4[5](u_pad0_geo, u_pad1_geo, u_pad2_geo, u_pad3_geo, u_pad4_geo);
    vec4 padDyn[5] = vec4[5](u_pad0_dyn, u_pad1_dyn, u_pad2_dyn, u_pad3_dyn, u_pad4_dyn);
    vec4 fishPos[5] = vec4[5](u_fish0_pos, u_fish1_pos, u_fish2_pos, u_fish3_pos, u_fish4_pos);
    vec4 fishAttr[5] = vec4[5](u_fish0_attr, u_fish1_attr, u_fish2_attr, u_fish3_attr, u_fish4_attr);

    // --- Interactive Coordinates ---
    vec2 pointerP = u_pointer;
    pointerP.x *= aspect;

    vec2 keystrokeP = u_keystroke_pos;
    keystrokeP.x *= aspect;

    vec2 beatCenterP = u_beat_center;
    beatCenterP.x *= aspect;

    float t = u_time * u_vortex_speed;
    float mouseSpeed = length(u_pointer_vel);

    // ------------------------------------------------------------------------
    // 1. Water Surface Wave Dynamics (Tranquil & Glassy)
    // ------------------------------------------------------------------------
    // Ambient gentle surface ripples
    vec2 rippleUV = p * 16.0 + u_ambient_drift * 2.0;
    float wave1 = sin(rippleUV.x * 1.8 + t * 1.5) * cos(rippleUV.y * 1.5 - t * 1.2);
    float wave2 = cos(rippleUV.x * 2.5 - t * 1.8) * sin(rippleUV.y * 2.0 + t * 1.5);
    float waveHeight = (wave1 + wave2 * 0.6) * 0.0035;

    // Keystroke concentric raindrop ripples (gentle droplets)
    if (u_keystroke_energy > 0.01) {
        float rDist = length(p - keystrokeP);
        float rainWave = sin(rDist * 36.0 - t * 10.0) * exp(-rDist * 7.0) * u_keystroke_energy * 0.008;
        waveHeight += rainWave;
    }

    // Pointer movement water wake (smooth, natural displacement)
    float mouseDist = length(p - pointerP);
    float mouseWake = sin(mouseDist * 22.0 - t * 3.0) * exp(-mouseDist * 9.0) * mouseSpeed * 0.004;
    waveHeight += mouseWake;

    // Audio Sub-bass cymatic surface waves (subtle and soft)
    float beatDist = length(p - beatCenterP);
    float bassWave = sin(beatDist * 22.0 - t * 6.0) * exp(-beatDist * 5.0) * u_bass * 0.005;
    waveHeight += bassWave;

    // Lilypad acoustic rim ripples
    for (int k = 0; k < 5; ++k) {
        float padWaveAmp = padDyn[k].y;
        if (padWaveAmp > 0.005) {
            vec2 toPadK = p - padGeo[k].xy;
            float pDist = length(toPadK);
            float pRadius = padGeo[k].z * padDyn[k].z;
            float dRim = max(0.0, pDist - pRadius);
            float pWave = sin(dRim * 36.0 - padDyn[k].x) * exp(-dRim * 10.0) * padWaveAmp * 0.005;
            pWave *= smoothstep(0.0, 0.02, dRim);
            waveHeight += pWave;
        }
    }

    // Auth Failed squall (muted)
    if (u_shockwave_intensity > 0.01) {
        float squall = sin(p.x * 40.0 + t * 12.0) * cos(p.y * 36.0 - t * 10.0) * u_shockwave_intensity * 0.012;
        waveHeight += squall;
    }

    // Water surface normal for light refraction
    const float eps = 0.008;
    vec2 pDx = p + vec2(eps, 0.0);
    vec2 pDy = p + vec2(0.0, eps);
    vec2 ripDx = pDx * 16.0 + u_ambient_drift * 2.0;
    vec2 ripDy = pDy * 16.0 + u_ambient_drift * 2.0;
    float hDx = (sin(ripDx.x * 1.8 + t * 1.5) * cos(ripDx.y * 1.5 - t * 1.2) + cos(ripDx.x * 2.5 - t * 1.8) * sin(ripDx.y * 2.0 + t * 1.5) * 0.6) * 0.0035;
    float hDy = (sin(ripDy.x * 1.8 + t * 1.5) * cos(ripDy.y * 1.5 - t * 1.2) + cos(ripDy.x * 2.5 - t * 1.8) * sin(ripDy.y * 2.0 + t * 1.5) * 0.6) * 0.0035;
    vec2 waterGradient = vec2(hDx - (wave1 + wave2 * 0.6) * 0.0035, hDy - (wave1 + wave2 * 0.6) * 0.0035) / eps;
    vec3 waterNormal = normalize(vec3(-waterGradient.x * 0.8, -waterGradient.y * 0.8, 0.65));

    // Refracted UV for looking through the water volume onto the pond bed
    vec2 refrUV = p + waterNormal.xy * 0.020;

    // ------------------------------------------------------------------------
    // 2. Riverbed Pebbles, Granite & Mossy Substrate
    // ------------------------------------------------------------------------
    vec3 pebbleVor = voronoiPebbles(refrUV * 12.0);
    float pebbleDist = pebbleVor.x;
    vec2 pebbleRand = pebbleVor.yz;

    // Palette blending for pebbles
    vec3 pebbleCol1 = u_color_pebbles.rgb;
    vec3 pebbleCol2 = u_color_pebbles.rgb * vec3(0.7, 0.8, 0.75); // Slate riverbed
    vec3 pebbleCol3 = vec3(0.12, 0.22, 0.15);                     // Submerged moss green

    vec3 bedColor = mix(pebbleCol1, pebbleCol2, pebbleRand.x);
    // Moss patches nestled in rock crevices
    float moss = smoothstep(0.45, 0.70, fbm(refrUV * 18.0));
    bedColor = mix(bedColor, pebbleCol3, moss * 0.7);

    // Pebble 3D bevel shading
    float pebbleBevel = smoothstep(0.04, 0.15, pebbleDist);
    bedColor *= (0.65 + 0.35 * pebbleBevel);

    // Sunlight Caustics Network dancing across riverbed
    float caustics = evaluateCaustics(refrUV, t) * (0.85 + u_treble * 0.35);
    bedColor += u_color_caustics.rgb * caustics * 0.75;

    // ------------------------------------------------------------------------
    // 3. Multi-Agent Nishikigoi School (5 Dynamic Koi Slots)
    // ------------------------------------------------------------------------
    float totalShadow = 0.0;
    float totalFishMask = 0.0;
    vec3 totalFishColor = vec3(0.0);
    float audioFlick = u_bass * 0.20;

    for (int i = 0; i < 5; ++i) {
        vec2 headPos = fishPos[i].xy;
        vec2 heading = fishPos[i].zw;
        float fishLen = fishAttr[i].x;
        float cadence = fishAttr[i].y;
        int variety = int(fishAttr[i].z + 0.5);
        float depth = fishAttr[i].w;

        float shad = 0.0;
        vec3 fCol = vec3(0.0);
        float mask = evaluateKoi(p, headPos, heading, fishLen, cadence, variety, depth, audioFlick, shad, fCol);

        totalShadow = max(totalShadow, shad);
        if (mask > 0.01) {
            float blendWeight = mask * (1.0 - depth * 0.35);
            totalFishColor = mix(totalFishColor, fCol, blendWeight);
            totalFishMask = max(totalFishMask, mask);
        }
    }

    // Apply fish drop shadow to riverbed
    bedColor *= (1.0 - totalShadow * 0.65);

    // Composite fish over riverbed
    vec3 pondContent = mix(bedColor, totalFishColor, totalFishMask);

    // ------------------------------------------------------------------------
    // 4. Floating Lily Pads (5 Animated Nymphaeaceae)
    // ------------------------------------------------------------------------
    float totalPadShadow = 0.0;
    float totalPadMask = 0.0;
    vec3 totalPadColor = vec3(0.0);

    for (int k = 0; k < 5; ++k) {
        vec2 padCenter = padGeo[k].xy;
        float padRadius = padGeo[k].z * padDyn[k].z;
        float padNotch = padGeo[k].w;
        int padType = int(padDyn[k].w + 0.5);

        float pShad = 0.0;
        vec3 pCol = vec3(0.0);
        float pMask = evaluateLilyPad(p, padCenter, padRadius, padNotch, t, padType, pShad, pCol);
        totalPadShadow = max(totalPadShadow, pShad);
        if (pMask > 0.01) {
            totalPadColor = mix(totalPadColor, pCol, pMask);
            totalPadMask = max(totalPadMask, pMask);
        }
    }

    // Apply lily pad shadows
    pondContent *= (1.0 - totalPadShadow * 0.70);
    pondContent = mix(pondContent, totalPadColor, totalPadMask);

    // ------------------------------------------------------------------------
    // 5. Crystal Clear Water Volume, Depth Absorption & Sky Fresnel
    // ------------------------------------------------------------------------
    vec3 waterTint = u_color_water.rgb;
    vec3 finalColor = mix(pondContent, waterTint, 0.22);

    // Surface specular sunlight glint from sky reflection
    vec3 sunLight = normalize(vec3(0.45, 0.55, 0.75));
    vec3 eyeDir = vec3(0.0, 0.0, 1.0);
    vec3 halfVec = normalize(sunLight + eyeDir);
    float waterSpec = pow(clamp(dot(waterNormal, halfVec), 0.0, 1.0), 32.0);
    finalColor += vec3(waterSpec * 0.85);

    // Keystroke glowing food pellets sinking in water
    if (u_keystroke_energy > 0.01) {
        float pelletDist = length(p - keystrokeP);
        float pelletGlow = exp(-pelletDist * 32.0) * (0.8 + 0.5 * sin(t * 8.0)) * u_keystroke_energy;
        finalColor += u_color_accent.rgb * pelletGlow * 2.0;
    }

    // Auth Failed Lightning Flash
    if (u_shockwave_intensity > 0.01) {
        float lightningFlash = u_shockwave_intensity * (0.7 + 0.3 * sin(t * 40.0));
        finalColor += vec3(0.85, 0.90, 1.0) * lightningFlash * 0.75;
    }

    fragColor = vec4(finalColor, 1.0) * qt_Opacity;
}
